// ECommerceProductManagement/ecommerce-ui/src/components/Navbar.jsx
import { useState } from "react";
import { Link, useLocation, useNavigate, useSearchParams } from "react-router-dom";
import { useCart } from "../hooks/useCart";
import { useAuth } from "../auth/useAuth";
import "../styles/main.css";

function Navbar() {
  const { isAuthenticated, user, logout } = useAuth();
  const { totalItems } = useCart();
  const location = useLocation();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [searchText, setSearchText] = useState(searchParams.get("q") ?? "");
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const sellerRoles = ["Admin", "ProductManager", "ContentExecutive"];
  const canAccessSellerConsole = sellerRoles.includes(user?.role ?? "");

  const onLogout = () => {
    setIsMenuOpen(false);
    logout();
    navigate("/auth/login");
  };

  const isActive = (path) => location.pathname.startsWith(path);
  const isCustomerView = location.pathname.startsWith("/customer");

  const onSearchSubmit = (event) => {
    event.preventDefault();
    const nextQuery = searchText.trim();
    const nextParams = new URLSearchParams();

    if (nextQuery) {
      nextParams.set("q", nextQuery);
    }

    navigate({
      pathname: "/customer/products",
      search: nextParams.toString() ? `?${nextParams.toString()}` : "",
    });
  };

  return (
    <>
      <nav className="navbar storefront-nav">
        <div className="nav-brand">
          <Link className="brand-lockup" to="/customer/products">
            <span className="brand-badge">epm</span>
            <div>
              <h2>ShopSphere</h2>
            </div>
           </Link>
          </div>

        <form className="nav-search-shell" onSubmit={onSearchSubmit}>
          <span className="nav-search-tag">All</span>
          <input
            className="nav-search"
            onChange={(event) => setSearchText(event.target.value)}
            placeholder="Search products, brands and departments"
            value={searchText}
          />
          <button className="nav-search-tag search-cta nav-search-button" type="submit">
            Search
          </button>
        </form>

        <div className="nav-links nav-links-utility">
          <Link className={isActive("/customer") ? "active" : ""} to="/customer/products">
            Storefront
          </Link>
          <Link className={isActive("/customer/cart") ? "active cart-link" : "cart-link"} to="/customer/cart">
            Cart
            {totalItems > 0 ? <span className="cart-count">{totalItems}</span> : null}
          </Link>

          {isAuthenticated ? (
            <>
              {canAccessSellerConsole ? (
                <Link className={isActive("/admin/products") ? "active" : ""} to="/admin/products">
                  Seller Console
                </Link>
              ) : null}
              {user?.role === "Admin" ? (
                              <>

                  <Link
                    className={isActive("/admin/dashboard") ? "active" : ""}
                    to="/admin/dashboard"
                  >
                    Dashboard
                  </Link>
                  <Link
                    className={isActive("/admin/workflow") ? "active" : ""}
                    to="/admin/workflow"
                  >
                    Workflow
                  </Link>
                  <Link
                    className={isActive("/admin/reports") ? "active" : ""}
                    to="/admin/reports"
                  >
                    Reports
                  </Link>
                </>
              ) : null}
              <div className="account-menu">
                <button
                  aria-expanded={isMenuOpen}
                  className="nav-button account-trigger"
                  onClick={() => setIsMenuOpen((current) => !current)}
                  type="button"
                >
                  {user?.name}
                  <span className="account-caret">{isMenuOpen ? "▲" : "▼"}</span>
                </button>

                {isMenuOpen ? (
                  <div className="account-dropdown">
                    <p className="account-name">{user?.name}</p>
                    <p className="account-role">{user?.role}</p>
                    <button className="account-dropdown-button" onClick={onLogout} type="button">
                      Logout
                    </button>
                  </div>
                ) : null}
              </div>
            </>
          ) : (
            <>
              <Link className={isActive("/auth/login") ? "active" : ""} to="/auth/login">
                Sign in
              </Link>
              <Link className={isActive("/auth/signup") ? "active" : ""} to="/auth/signup">
                Register
              </Link>
            </>
          )}
        </div>
      </nav>

      {isCustomerView ? (
        <div className="subnav-bar">
          <Link to="/customer/products">Today's Deals</Link>
          <Link to="/customer/products?category=Electronics">Electronics</Link>
          <Link to="/customer/products?category=Fashion">Fashion</Link>
          <Link to="/customer/products?category=Kitchen">Home & Kitchen</Link>
          <Link to="/customer/products?category=Fitness">Fitness</Link>
          <Link to="/customer/products?q=featured">Prime Preview</Link>
        </div>
      ) : null}
    </>
  );
}

export default Navbar;

// ECommerceProductManagement/ecommerce-ui/src/app/shared/navbar.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { NavigationEnd, Router, RouterLink, RouterLinkActive } from '@angular/router';
import { filter } from 'rxjs';
import { AuthService } from '../services/auth.service';
import { CartService } from '../services/cart.service';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterLink, RouterLinkActive],
  templateUrl: './navbar.component.html',
})
export class NavbarComponent {
  protected searchText = '';
  protected readonly isMenuOpen = signal(false);
  protected readonly totalItems = this.cartService.totalItems;
  protected readonly isAuthenticated = this.authService.isAuthenticated;
  protected readonly user = this.authService.user;
  protected readonly isCustomer = computed(() => this.authService.user()?.role === 'Customer');
  protected readonly canAccessSellerConsole = computed(() =>
    ['Admin', 'ProductManager', 'ContentExecutive'].includes(this.authService.user()?.role ?? '')
  );
  protected readonly isCustomerView = signal(true);

  constructor(
    private readonly authService: AuthService,
    private readonly cartService: CartService,
    private readonly router: Router
  ) {
    this.syncWithRoute(router.url);
    this.router.events
      .pipe(filter((event) => event instanceof NavigationEnd))
      .subscribe((event) => this.syncWithRoute((event as NavigationEnd).urlAfterRedirects));
  }

  protected onLogout(): void {
    this.isMenuOpen.set(false);
    this.cartService.clear();
    this.authService.logout();
    void this.router.navigate(['/auth/login']);
  }

  protected onSearchSubmit(): void {
    const nextQuery = this.searchText.trim();
    void this.router.navigate(['/customer/products'], {
      queryParams: nextQuery ? { q: nextQuery } : {},
    });
  }

  protected toggleMenu(): void {
    this.isMenuOpen.update((value) => !value);
  }

  private syncWithRoute(url: string): void {
    const [path, search] = url.split('?');
    this.isCustomerView.set(path.startsWith('/customer'));
    const params = new URLSearchParams(search ?? '');
    this.searchText = params.get('q') ?? '';
  }
}

<nav class="navbar storefront-nav">
  <div class="nav-brand">
    <a class="brand-lockup" routerLink="/customer/products">
      <span class="brand-badge">epm</span>
      <div>
        <h2>ShopSphere</h2>
      </div>
    </a>
  </div>

  <form class="nav-search-shell" (ngSubmit)="onSearchSubmit()">
    <span class="nav-search-tag">All</span>
    <input
      class="nav-search"
      [(ngModel)]="searchText"
      name="navbarSearch"
      placeholder="Search products, brands and departments"
    />
    <button class="nav-search-tag search-cta nav-search-button" type="submit">Search</button>
  </form>

  <div class="nav-links nav-links-utility">
    <a routerLink="/customer/products" routerLinkActive="active">Storefront</a>
    @if (isCustomer()) {
      <a routerLink="/customer/cart" routerLinkActive="active" class="cart-link">
        Cart
        @if (totalItems() > 0) {
          <span class="cart-count">{{ totalItems() }}</span>
        }
      </a>
    }

    @if (isAuthenticated()) {
      @if (canAccessSellerConsole()) {
        <a routerLink="/admin/products" routerLinkActive="active">Seller Console</a>
      }
      @if (user()?.role === 'Admin') {
        <a routerLink="/admin/dashboard" routerLinkActive="active">Dashboard</a>
        <a routerLink="/admin/workflow" routerLinkActive="active">Workflow</a>
        <a routerLink="/admin/reports" routerLinkActive="active">Reports</a>
      }

      <div class="account-menu">
        <button
          class="nav-button account-trigger"
          type="button"
          [attr.aria-expanded]="isMenuOpen()"
          (click)="toggleMenu()"
        >
          {{ user()?.name }}
          <span class="account-caret">{{ isMenuOpen() ? '▲' : '▼' }}</span>
        </button>

        @if (isMenuOpen()) {
          <div class="account-dropdown">
            <p class="account-name">{{ user()?.name }}</p>
            <p class="account-role">{{ user()?.role }}</p>
            <button class="account-dropdown-button" type="button" (click)="onLogout()">
              Logout
            </button>
          </div>
        }
      </div>
    } @else {
      <a routerLink="/auth/login" routerLinkActive="active">Sign in</a>
      <a routerLink="/auth/signup" routerLinkActive="active">Register</a>
    }
  </div>
</nav>

@if (isCustomerView()) {
  <div class="subnav-bar">
    <a routerLink="/customer/products">Today's Deals</a>
    <a routerLink="/customer/products" [queryParams]="{ category: 'Electronics' }">Electronics</a>
    <a routerLink="/customer/products" [queryParams]="{ category: 'Fashion' }">Fashion</a>
    <a routerLink="/customer/products" [queryParams]="{ category: 'Kitchen' }">Home &amp; Kitchen</a>
    <a routerLink="/customer/products" [queryParams]="{ category: 'Fitness' }">Fitness</a>
    <a routerLink="/customer/products" [queryParams]="{ q: 'featured' }">Prime Preview</a>
  </div>
}
