// ECommerceProductManagement/ecommerce-ui/src/components/ProductCard.jsx
import { useNavigate } from "react-router-dom";

function ProductCard({ product, mode = "admin" }) {
  const navigate = useNavigate();
  const destination =
    mode === "customer"
      ? `/customer/products/${product.id}`
      : `/admin/products/${product.id}`;
  const rating = (4 + ((product.sellingPrice || 0) % 10) / 20).toFixed(1);
  const reviewCount = 120 + ((product.stockQuantity || 0) * 7);
  const isCustomer = mode === "customer";

  return (
    <article
      className={isCustomer ? "product-card marketplace-card" : "card product-card"}
      onClick={() => navigate(destination)}
    >
      <div className="product-image-shell">
        <img alt={product.name} className="product-image" src={product.primaryImageUrl} />
        {isCustomer ? <span className="deal-badge">Limited time deal</span> : null}
      </div>

      <div className="product-copy">
        <div className="pill-row">
          <span className="pill">{product.categoryName || "General"}</span>
          <span className={`pill status-${String(product.status).toLowerCase()}`}>
            {product.status}
          </span>
        </div>

        <h3 className="product-title">{product.name}</h3>
        <p className="muted product-brand">{product.brand}</p>

        {isCustomer ? (
          <div className="rating-row">
            <span className="rating-score">{rating}</span>
            <span className="rating-stars">★★★★★</span>
            <span className="muted">({reviewCount})</span>
          </div>
        ) : null}

        <p className="price">Rs. {Number(product.sellingPrice || 0).toLocaleString("en-IN")}</p>
        <p className="muted">SKU: {product.sku}</p>
        <p className={product.stockQuantity > 0 ? "stock-good" : "stock-low"}>
          {product.stockQuantity > 0
            ? `In stock: ${product.stockQuantity} units`
            : "Currently unavailable"}
        </p>
      </div>
    </article>
  );
}

export default ProductCard;

// ECommerceProductManagement/ecommerce-ui-backup/src/app/shared/product-card.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { Router } from '@angular/router';
import { Product } from '../models';
import { formatServerDate } from '../utils/date-format';

@Component({
  selector: 'app-product-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './product-card.component.html',
})
export class ProductCardComponent {
  private readonly statusLabels = [
    'Draft',
    'InEnrichment',
    'ReadyForReview',
    'Approved',
    'Published',
    'Rejected',
    'Archived',
  ];

  @Input({ required: true }) product!: Product;
  @Input() mode: 'admin' | 'customer' = 'admin';

  constructor(private readonly router: Router) {}

  protected open(): void {
    const destination =
      this.mode === 'customer'
        ? `/customer/products/${this.product.id}`
        : `/admin/products/${this.product.id}`;
    void this.router.navigateByUrl(destination);
  }

  protected get rating(): string {
    return (4 + ((this.product?.sellingPrice || 0) % 10) / 20).toFixed(1);
  }

  protected get reviewCount(): number {
    return 120 + ((this.product?.stockQuantity || 0) * 7);
  }

  protected get statusLabel(): string {
    const status = this.product?.status;
    if (typeof status === 'number') {
      return this.statusLabels[status] ?? 'Unknown';
    }

    return status || 'Unknown';
  }

  protected get statusClass(): string {
    return `pill status-${this.statusLabel.toLowerCase()}`;
  }

  protected get statusTimestamp(): string {
    return formatServerDate(this.product?.updatedAt || this.product?.createdAt);
  }
}

<article
  [class]="mode === 'customer' ? 'product-card marketplace-card' : 'card product-card'"
  (click)="open()"
>
  <div class="product-image-shell">
    <img [src]="product.primaryImageUrl" [alt]="product.name" class="product-image" />
    @if (mode === 'customer') {
      <span class="deal-badge">Limited time deal</span>
    }
  </div>

  <div class="product-copy">
    <div class="pill-row">
      <span class="pill">{{ product.categoryName || 'General' }}</span>
      <span [class]="statusClass">
        {{ statusLabel }}
      </span>
    </div>
    <span class="status-meta">{{ statusTimestamp }}</span>

    <h3 class="product-title">{{ product.name }}</h3>
    <p class="muted product-brand">{{ product.brand }}</p>

    @if (mode === 'customer') {
      <div class="rating-row">
        <span class="rating-score">{{ rating }}</span>
        <span class="rating-stars">★★★★★</span>
        <span class="muted">({{ reviewCount }})</span>
      </div>
    }

    <p class="price">Rs. {{ product.sellingPrice || 0 | number: '1.0-0' }}</p>
    <p class="muted">SKU: {{ product.sku }}</p>
    <p [class]="product.stockQuantity > 0 ? 'stock-good' : 'stock-low'">
      {{
        product.stockQuantity > 0
          ? 'In stock: ' + product.stockQuantity + ' units'
          : 'Currently unavailable'
      }}
    </p>
  </div>
</article>
